# configuration file for the unconditional training

# 1. Image processing
preprocessing:
  # image size or resolution to resize
  resolution: 64
  # batch size for dataloader
  batch_size: 64

# 2. Model
model:
  in_channels: 3
  out_channels: 3
  layers_per_block: 2
  block_out_channels: !!python/tuple
  - "DownBlock2D"  # a regular ResNet downsampling block
  - "DownBlock2D"
  - "DownBlock2D"
  - "DownBlock2D"
  - "AttnDownBlock2D"  # a ResNet downsampling block with spatial self-attention
  - "AttnDownBlock2D"
  up_block_types: !!python/tuple
  - "AttnUpBlock2D",
  - "AttnUpBlock2D",  # a ResNet upsampling block with spatial self-attention
  - "UpBlock2D",
  - "UpBlock2D",  # a regular ResNet upsampling block
  - "UpBlock2D",
  - "UpBlock2D",