block_out_channels: !!python/tuple
- 128
- 128
- 256
- 256
- 512
- 512
down_block_types: !!python/tuple
- DownBlock2D
- DownBlock2D
- DownBlock2D
- DownBlock2D
- AttnDownBlock2D
- AttnDownBlock2D
in_channels: 3
layers_per_block: 2
out_channels: 3